import networkx as nx
import matplotlib.pyplot as plt
from collections import defaultdict

# Sample data provided in the format of strings
data = """
Added Eric-Lesser-3 (Eric Lesser) as a politically relevant friend connected to Valerie-Jarrett-2.
Added Tlcarter777 (Troy Carter) as a politically relevant friend connected to Valerie-Jarrett-2.
Added Van-Jones (Van Jones) as a politically relevant friend connected to Valerie-Jarrett-2.
Added rico_suave (Jared Williams) as a politically relevant friend connected to Valerie-Jarrett-2.
Added DeRayM (DeRay Mckesson) as a politically relevant friend connected to Valerie-Jarrett-2.
Added bob-sherman-303 (Robert Sherman) as a politically relevant friend connected to Eric-Lesser-3.
Added Jeff-Zeleny-1 (Jeff Zeleny) as a politically relevant friend connected to Eric-Lesser-3.
Added stephanie-cutter (stephanie cutter) as a politically relevant friend connected to Eric-Lesser-3.
Added JeremyBird (Jeremy Bird) as a politically relevant friend connected to Eric-Lesser-3.
Added Nancy-Ann-DeParle (Nancy-Ann DeParle) as a politically relevant friend connected to Eric-Lesser-3.
Added marcusbrown65 (Marcus Brown) as a politically relevant friend connected to Tlcarter777.
Added TheCheckFinder (Michael Williams) as a politically relevant friend connected to Tlcarter777.
Added John-Biggs (John Biggs) as a politically relevant friend connected to Tlcarter777.
Added SorayaDarabi (Soraya Darabi) as a politically relevant friend connected to Tlcarter777.
Added jmstein8 (Jon Stein) as a politically relevant friend connected to Tlcarter777.
Added Wendy-Smith-38 (Wendy Smith) as a politically relevant friend connected to Van-Jones.
Added Michael-Huttner-2 (Michael Huttner) as a politically relevant friend connected to Van-Jones.
Added Will-Byrne-1 (Will Byrne) as a politically relevant friend connected to Van-Jones.
Added Garlin (Garlin Gilchrist II) as a politically relevant friend connected to Van-Jones.
Added SaraWalker_ (Sara Walker) as a politically relevant friend connected to rico_suave.
Added Jessica-Matthews-23 (Jessica Matthews) as a politically relevant friend connected to rico_suave.
Added Dwight-Bush (Dwight Bush) as a politically relevant friend connected to rico_suave.
Added Valerie-Jarrett-2 (Valerie Jarrett) as a politically relevant friend connected to rico_suave.
Added Garrett-Smith-40 (Garrett Smith) as a politically relevant friend connected to rico_suave.
Added Patrick-Frank (Patrick Frank) as a politically relevant friend connected to DeRayM.
Added Ben-Austen (Ben Austen) as a politically relevant friend connected to DeRayM.
Added Faiz-Shakir-1 (Faiz Shakir) as a politically relevant friend connected to DeRayM.
Added Davante-Lewis (Davante Lewis) as a politically relevant friend connected to DeRayM.
Added Michael-Sam (Michael Sam) as a politically relevant friend connected to DeRayM.
Added Joseph-Hanley-21 (Joseph Hanley) as a politically relevant friend connected to bob-sherman-303.
Added Jacqueline-Becerra-3 (Jacqueline Becerra) as a politically relevant friend connected to bob-sherman-303.
Added Vicki-R-KennedyMA (Vicki Kennedy) as a politically relevant friend connected to bob-sherman-303.
Added Paul-Hodes (Paul Hodes) as a politically relevant friend connected to bob-sherman-303.
Added James-Costos (James Costos) as a politically relevant friend connected to bob-sherman-303.
Added Brian-Rosenthal-10 (Brian Rosenthal) as a politically relevant friend connected to Jeff-Zeleny-1.
Added Karen-Finney (Karen Finney) as a politically relevant friend connected to Jeff-Zeleny-1.
Added allenebaker (Allen Baker) as a politically relevant friend connected to Jeff-Zeleny-1.
Added Chuck-Larson-2 (Chuck Larson) as a politically relevant friend connected to Jeff-Zeleny-1.
Added michaelrobinsonbyrd (Michael Byrd) as a politically relevant friend connected to Jeff-Zeleny-1.
Added Julianna-Goldman (Julianna Goldman) as a politically relevant friend connected to stephanie-cutter.
Added Matt-Bai (Matt Bai) as a politically relevant friend connected to stephanie-cutter.
Added Sarah-Bianchi-9 (Sarah Bianchi) as a politically relevant friend connected to stephanie-cutter.
Added Carol-Browner (Carol Browner) as a politically relevant friend connected to stephanie-cutter.
Added DHerman0 (Daniel Herman) as a politically relevant friend connected to JeremyBird.
Added trevorn (Trevor Neilson) as a politically relevant friend connected to JeremyBird.
Added David-Levine-29 (David Levine) as a politically relevant friend connected to JeremyBird.
Added Bill-Nettles (Bill Nettles) as a politically relevant friend connected to JeremyBird.
Added Tina-Seaman (Tina Brown) as a politically relevant friend connected to JeremyBird.
Added Brian-McKeon-14 (Brian McKeon) as a politically relevant friend connected to Nancy-Ann-DeParle.
Added Chip-Kahn (Chip Kahn) as a politically relevant friend connected to Nancy-Ann-DeParle.
Added Chiquita-Brooks-LaSure (Chiquita Brooks-LaSure) as a politically relevant friend connected to Nancy-Ann-DeParle.
Added Tim-Hill-67 (Tim Hill) as a politically relevant friend connected to Nancy-Ann-DeParle.
Added James-Kvaal (James Kvaal) as a politically relevant friend connected to Nancy-Ann-DeParle.
Added Michael-Brown-1130 (Michael Brown) as a politically relevant friend connected to marcusbrown65.
Added acjohnson (Andrew Johnson) as a politically relevant friend connected to marcusbrown65.
Added Sam-Cohen-22 (Sam Cohen) as a politically relevant friend connected to marcusbrown65.
Added Andreanromero (Andrea Romero) as a politically relevant friend connected to marcusbrown65.
Added todd-Hunter-16 (todd Hunter) as a politically relevant friend connected to TheCheckFinder.
Added allenjwest (Allen West) as a politically relevant friend connected to TheCheckFinder.
Added ChrisJxx (Chris Jordan) as a politically relevant friend connected to TheCheckFinder.
Added Carl-Martin-1 (Carl Martin) as a politically relevant friend connected to TheCheckFinder.
Added Walter-Little-1 (Walter Little) as a politically relevant friend connected to TheCheckFinder.
Added nicolenerd (Nicole Lee) as a politically relevant friend connected to John-Biggs.
Added Joel-Johnson (Joel Johnson) as a politically relevant friend connected to John-Biggs.
Added djhardy (Darryl Hardy) as a politically relevant friend connected to John-Biggs.
Added Rob-Anderson-87 (Rob Anderson) as a politically relevant friend connected to John-Biggs.
Added jessethomasjess3 (Jesse Thomas) as a politically relevant friend connected to John-Biggs.
Added chriscarneyhair (Chris Carney) as a politically relevant friend connected to SorayaDarabi.
Added Cyrus-Habib (Cyrus Habib) as a politically relevant friend connected to SorayaDarabi.
Added MaxLugavere (Max Lugavere) as a politically relevant friend connected to SorayaDarabi.
Added Elizabeth-Brown-51 (Elizabeth Brown) as a politically relevant friend connected to SorayaDarabi.
Added Jenna-Arnold-1 (Jenna Arnold) as a politically relevant friend connected to SorayaDarabi.
Added Evan-Lloyd-2 (Evan Lloyd) as a politically relevant friend connected to jmstein8.
Added John-Kelly-357 (John Kelly) as a politically relevant friend connected to jmstein8.
Added itsalexsmith (Alex Smith) as a politically relevant friend connected to jmstein8.
Added Jeremy-Gilbert (Jeremy Gilbert) as a politically relevant friend connected to jmstein8.
Added Kevin-White-2 (Kevin White) as a politically relevant friend connected to jmstein8.
Added JakeSiewert1 (Jake Siewert) as a politically relevant friend connected to Wendy-Smith-38.
Added Lenny-Stern (Lenny Stern) as a politically relevant friend connected to Wendy-Smith-38.
Added Christopher-Clarke-27 (Christopher Clarke) as a politically relevant friend connected to Wendy-Smith-38.
Added Scott-Cohen-23 (Scott Cohen) as a politically relevant friend connected to Wendy-Smith-38.
Added Andrew-Solomon-16 (Andrew Solomon) as a politically relevant friend connected to Michael-Huttner-2.
Added LouisianaMattBailey (Matt Bailey) as a politically relevant friend connected to Michael-Huttner-2.
Added TrevorKincaid (Trevor Kincaid) as a politically relevant friend connected to Michael-Huttner-2.
Added Arshad-Hasan (Arshad Hasan) as a politically relevant friend connected to Michael-Huttner-2.
Added David-Kramer-10 (David Kramer) as a politically relevant friend connected to Michael-Huttner-2.
Added alexhsmith (Alex Smith) as a politically relevant friend connected to Will-Byrne-1.
Added David-Lloyd-2 (David Lloyd) as a politically relevant friend connected to Will-Byrne-1.
Added steelfloyd (Stephen Lloyd) as a politically relevant friend connected to Will-Byrne-1.
Added Peter-Murray-32 (Peter Murray) as a politically relevant friend connected to Will-Byrne-1.
Added allaspiaggia (Sarah Thomas) as a politically relevant friend connected to Will-Byrne-1.
Added AshrafMarwan1 (Ashraf Marwan) as a politically relevant friend connected to SaraWalker_.
Added Edward-Ellis-3 (Edward Ellis) as a politically relevant friend connected to SaraWalker_.
Added Malia-Ann (Malia Ann) as a politically relevant friend connected to SaraWalker_.
Added Christopher-Ward-26 (Christopher Ward) as a politically relevant friend connected to SaraWalker_.
Added BenDMahon (Ben Mahon) as a politically relevant friend connected to Jessica-Matthews-23.
Added ThomasDietz (Thomas Dietz) as a politically relevant friend connected to Jessica-Matthews-23.
Added John-Robinson-173 (John Robinson) as a politically relevant friend connected to Jessica-Matthews-23.
Added Roberto-Campos-15 (Roberto Campos) as a politically relevant friend connected to Jessica-Matthews-23.
Added James-Winebrake (James Patrick) as a politically relevant friend connected to Dwight-Bush.
Added Abdul-Kareem (Abdul Kareem) as a politically relevant friend connected to Dwight-Bush.
Added kevinyu (Kevin Yu) as a politically relevant friend connected to Dwight-Bush.
Added Andy-Smith-12 (Andy Smith) as a politically relevant friend connected to Dwight-Bush.
Added Henry-Sisson (Henry Sisson) as a politically relevant friend connected to Dwight-Bush.
Added chrisryan1050 (Chris Ryan) as a politically relevant friend connected to Valerie-Jarrett-2.
Added Jonathan-Neman (Jonathan Neman) as a politically relevant friend connected to Valerie-Jarrett-2.
Added carlraymua (Carl Ray) as a politically relevant friend connected to Valerie-Jarrett-2.
Added Fay-Hartog-Levin (Fay Hartog-Levin) as a politically relevant friend connected to Valerie-Jarrett-2.
Added Deval-Patrick (Deval Patrick) as a politically relevant friend connected to Valerie-Jarrett-2.
Added pgallen33 (Patrick Green) as a politically relevant friend connected to Garrett-Smith-40.
Added greghall12 (Greg Hall) as a politically relevant friend connected to Garrett-Smith-40.
Added Ben-Mahon (Ben Mahon) as a politically relevant friend connected to Garrett-Smith-40.
Added Christian-Castillo-4 (Christian Castillo) as a politically relevant friend connected to Garrett-Smith-40.
Added Rick-Klein-9 (Rick Klein) as a politically relevant friend connected to Garrett-Smith-40.
Added BenSchott (Ben Schott) as a politically relevant friend connected to Patrick-Frank.
Added David-Marsh (David Marsh) as a politically relevant friend connected to Patrick-Frank.
Added Dylan-Roberts-1 (Dylan Roberts) as a politically relevant friend connected to Patrick-Frank.
Added Thomas-Berry-11 (Thomas Berry) as a politically relevant friend connected to Patrick-Frank.
Added Brandon-English (Brandon English) as a politically relevant friend connected to Patrick-Frank.
Added Ozier-Muhammad (Ozier Muhammad) as a politically relevant friend connected to Ben-Austen.
Added sjmurphy (Sarah Murphy) as a politically relevant friend connected to Ben-Austen.
Added saschapenn (Alexander Penn) as a politically relevant friend connected to Ben-Austen.
Added jecummin (Jason Cummings) as a politically relevant friend connected to Ben-Austen.
Added KLB0615 (Keith Barnes) as a politically relevant friend connected to Faiz-Shakir-1.
Added Ramesh-Srinivasan-2 (Ramesh Srinivasan) as a politically relevant friend connected to Faiz-Shakir-1.
Added Reema-Dodin (Reema Dodin) as a politically relevant friend connected to Faiz-Shakir-1.
Added Jayshah24 (Jay Shah) as a politically relevant friend connected to Faiz-Shakir-1.
Added Macon-Phillips (Macon Phillips) as a politically relevant friend connected to Faiz-Shakir-1.
Added Gary-Jackson-5 (Gary Jackson) as a politically relevant friend connected to Davante-Lewis.
Added Nicholas-Johnson-24 (Nicholas Johnson) as a politically relevant friend connected to Davante-Lewis.
Added cs_parsons (Cameron Parsons) as a politically relevant friend connected to Davante-Lewis.
Added morrisdavidw (David Morris) as a politically relevant friend connected to Davante-Lewis.
Added John-Berger-10 (John Berger) as a politically relevant friend connected to Davante-Lewis.
Added MichaelHarris (Michael Harris) as a politically relevant friend connected to Michael-Sam.
Added tsaboston (Tyler Anderson) as a politically relevant friend connected to Michael-Sam.
Added xatgm (Alexander Green) as a politically relevant friend connected to Michael-Sam.
Added thedavidbrand (David Robinson) as a politically relevant friend connected to Michael-Sam.
Added Max-Rosenthal-2 (Max Rosenthal) as a politically relevant friend connected to Michael-Sam.
Added Mark-Ciommo (Mark Ciommo) as a politically relevant friend connected to Joseph-Hanley-21.
Added PatrickMMahoney (Patrick Mahoney) as a politically relevant friend connected to Joseph-Hanley-21.
Added TomasGonzalez15 (Tomas Gonzalez) as a politically relevant friend connected to Joseph-Hanley-21.
Added David-Gordon-79 (David Gordon) as a politically relevant friend connected to Joseph-Hanley-21.
Added Michelle-Cruz-121 (Michelle Cruz) as a politically relevant friend connected to Jacqueline-Becerra-3.
Added ausssmit (Austin Smith) as a politically relevant friend connected to Jacqueline-Becerra-3.
Added Jason_Pelletier30 (Jason Pelletier) as a politically relevant friend connected to Jacqueline-Becerra-3.
Added Javier-Lopez-47 (Javier Lopez) as a politically relevant friend connected to Jacqueline-Becerra-3.
Added Marc-Goldberg-3 (Marc Goldberg) as a politically relevant friend connected to Paul-Hodes.
Added Edwin-Perlmutter (Edwin Perlmutter) as a politically relevant friend connected to Paul-Hodes.
Added dennisjfoley (Dennis Foley) as a politically relevant friend connected to Paul-Hodes.
Added Rufus-Gifford (Rufus Gifford) as a politically relevant friend connected to Paul-Hodes.
Added w-tucker (William Tucker) as a politically relevant friend connected to Paul-Hodes.
Added Desiree-Rogers (Desiree Rogers) as a politically relevant friend connected to James-Costos.
Added Michael-Morris-00 (Michael Morris) as a politically relevant friend connected to James-Costos.
Added Chuck-Robbins (Chuck Robbins) as a politically relevant friend connected to James-Costos.
Added Mia-Lehrer (Mia Lehrer) as a politically relevant friend connected to James-Costos.
Added Q8jumpbaby (Jose Antonio) as a politically relevant friend connected to James-Costos.
Added ChrisAnderson518 (Chris Anderson) as a politically relevant friend connected to Brian-Rosenthal-10.
Added Greg-Sharpe-2 (Greg Sharpe) as a politically relevant friend connected to Brian-Rosenthal-10.
Added Paul-Newton-22 (Paul Newton) as a politically relevant friend connected to Brian-Rosenthal-10.
Added Brad-Shaw-13 (Brad Shaw) as a politically relevant friend connected to Brian-Rosenthal-10.
Added Tommy-Gallagher-17 (Tommy Gallagher) as a politically relevant friend connected to Brian-Rosenthal-10.
Added Ilyse-Hogue (Ilyse Hogue) as a politically relevant friend connected to Karen-Finney.
Added pricehouseproperties (Jimmy Williams) as a politically relevant friend connected to Karen-Finney.
Added Michelle-Bernard-5 (Michelle Bernard) as a politically relevant friend connected to Karen-Finney.
Added Ryan-Grim-5 (Ryan Grim) as a politically relevant friend connected to Karen-Finney.
Added DavidBRogers (David Rogers) as a politically relevant friend connected to allenebaker.
Added HussainMirza (Hussain Mirza) as a politically relevant friend connected to allenebaker.
Added luke_flanagan (Luke Flanagan) as a politically relevant friend connected to allenebaker.
Added Marcus-Ambrose (Marcus Ambrose) as a politically relevant friend connected to allenebaker.
Added jeffkingisu (Jeff King) as a politically relevant friend connected to Chuck-Larson-2.
Added Howard-Friedman-20 (Howard Friedman) as a politically relevant friend connected to Chuck-Larson-2.
Added Frank-Chiodo-3 (Frank Chiodo) as a politically relevant friend connected to Chuck-Larson-2.
Added Mike-Henry-40 (Mike Henry) as a politically relevant friend connected to Chuck-Larson-2.
Added Johara4sa (James O'Hara) as a politically relevant friend connected to Chuck-Larson-2.
Added James-Rowland-23 (James Rowland) as a politically relevant friend connected to michaelrobinsonbyrd.
Added Martha-Miller-11 (Martha Miller) as a politically relevant friend connected to michaelrobinsonbyrd.
Added Lisa-Wagner-116 (Lisa Wagner) as a politically relevant friend connected to michaelrobinsonbyrd.
Added Steve-Thompson (Steve Thompson) as a politically relevant friend connected to michaelrobinsonbyrd.
Added OxyChaz (Charles Moran) as a politically relevant friend connected to michaelrobinsonbyrd.
Added Sally-Smith-11 (Sally Smith) as a politically relevant friend connected to Julianna-Goldman.
Added Michael-Goldman-44 (Michael Goldman) as a politically relevant friend connected to Julianna-Goldman.
Added rrkaplan18 (Rebecca Kaplan) as a politically relevant friend connected to Julianna-Goldman.
Added JasonFurman (Jason Furman) as a politically relevant friend connected to Julianna-Goldman.
Added Ryan-Lizza (Ryan Lizza) as a politically relevant friend connected to Matt-Bai.
Added Roger-Alex-Conant (Alex Conant) as a politically relevant friend connected to Matt-Bai.
Added William-Minor-9 (William Minor) as a politically relevant friend connected to Matt-Bai.
Added Marc-Ambinder (Marc Ambinder) as a politically relevant friend connected to Matt-Bai.
Added Steven-Clemons (Steven Clemons) as a politically relevant friend connected to Matt-Bai.
Added Ron-Klain (Ron Klain) as a politically relevant friend connected to Sarah-Bianchi-9.
Added Lvhernandez (Luis Hernandez) as a politically relevant friend connected to Sarah-Bianchi-9.
Added MLH57 (Michael Nutter) as a politically relevant friend connected to Sarah-Bianchi-9.
Added Kate-Aitken (Kate Aitken) as a politically relevant friend connected to Sarah-Bianchi-9.
Added Kevin-Bailey-Arlington (Kevin Bailey) as a politically relevant friend connected to Sarah-Bianchi-9.
Added Elizabeth-Littlefield-1 (Elizabeth Littlefield) as a politically relevant friend connected to Carol-Browner.
Added Bob-Perciasepe (Robert Perciasepe) as a politically relevant friend connected to Carol-Browner.
Added Fred-Hochberg (Fred Hochberg) as a politically relevant friend connected to Carol-Browner.
Added Cass-Sunstein (Cass Sunstein) as a politically relevant friend connected to Carol-Browner.
Added jpmcgurk (John McGurk) as a politically relevant friend connected to DHerman0.
Added KatieBMiller (Katie Miller) as a politically relevant friend connected to DHerman0.
Added schultzohio (Greg Schultz) as a politically relevant friend connected to DHerman0.
Added Austin-Lyle (Austin Lyle) as a politically relevant friend connected to DHerman0.
Added matthew-brennan-8 (Matt Brennan) as a politically relevant friend connected to DHerman0.
Added jamesacmcdermott (Jim McDermott) as a politically relevant friend connected to trevorn.
Added Naomi-Gleit (Naomi Gleit) as a politically relevant friend connected to trevorn.
Added joerag12 (Joe Ragland) as a politically relevant friend connected to trevorn.
Added James-Gilbert-16 (James Gilbert) as a politically relevant friend connected to trevorn.
Added Paul-Haggis (Paul Haggis) as a politically relevant friend connected to trevorn.
Added Boyd-Young-2 (Boyd Young) as a politically relevant friend connected to Bill-Nettles.
Added mcdougalljohn (John McDougall) as a politically relevant friend connected to Bill-Nettles.
Added hboydbrown (Boyd Brown) as a politically relevant friend connected to Bill-Nettles.
Added JamesSmithSC (James Smith) as a politically relevant friend connected to Bill-Nettles.
Added HarrisonJaime (Jaime Harrison) as a politically relevant friend connected to Bill-Nettles.
Added Tamaru2112 (James Moran) as a politically relevant friend connected to Tina-Seaman.
Added Mikeyj317 (Michael Johnson) as a politically relevant friend connected to Tina-Seaman.
Added Jason-Ng-1 (Jason Ng) as a politically relevant friend connected to Tina-Seaman.
Added Jim-Murphy (Jim Murphy) as a politically relevant friend connected to Tina-Seaman.
Added Jennifer-Simon-6 (Jennifer Simon) as a politically relevant friend connected to Brian-McKeon-14.
Added jonfiner (Jon Finer) as a politically relevant friend connected to Brian-McKeon-14.
Added Julianne-Smith-32 (Julianne Smith) as a politically relevant friend connected to Brian-McKeon-14.
Added Frank-Kendall-1 (Frank Kendall) as a politically relevant friend connected to Brian-McKeon-14.
Added Timothy-Heaphy (Timothy Heaphy) as a politically relevant friend connected to Brian-McKeon-14.
Added James-Greenwood-4 (James Greenwood) as a politically relevant friend connected to Chip-Kahn.
Added Tony-Sanchez-71 (Tony Sanchez) as a politically relevant friend connected to Chip-Kahn.
Added Tom-Fitzpatrick-11 (Tom Fitzpatrick) as a politically relevant friend connected to Chip-Kahn.
Added marylandrieu (Mary Landrieu) as a politically relevant friend connected to Chip-Kahn.
Added Austin-Willis-1 (Austin Willis) as a politically relevant friend connected to Chip-Kahn.
Added William-Bernstein-6 (William Bernstein) as a politically relevant friend connected to Chiquita-Brooks-LaSure.
Added nicolehwhite (Nicole White) as a politically relevant friend connected to Chiquita-Brooks-LaSure.
Added Mary-Mayhew-1 (Mary Mayhew) as a politically relevant friend connected to Tim-Hill-67.
Added Tracy-Jordan-LCSWC (Tracy Jordan) as a politically relevant friend connected to Tim-Hill-67.
Added Danny-Werfel (Danny Werfel) as a politically relevant friend connected to Tim-Hill-67.
Added Ian-Hill-20 (Ian Hill) as a politically relevant friend connected to Tim-Hill-67.
Added HMS211 (Haley Stevens) as a politically relevant friend connected to James-Kvaal.
Added Maya-Shankar (Maya Shankar) as a politically relevant friend connected to James-Kvaal.
Added Sam-Brown-42 (Sam Brown) as a politically relevant friend connected to James-Kvaal.
Added Dan-Pfeiffer-2 (Dan Pfeiffer) as a politically relevant friend connected to James-Kvaal.
Added Peter-Orszag (Peter Orszag) as a politically relevant friend connected to James-Kvaal.
Added Anthony-Martinez-943 (Anthony Martinez) as a politically relevant friend connected to Michael-Brown-1130.
Added Katie-Brown-28 (Katie Brown) as a politically relevant friend connected to Michael-Brown-1130.
Added Taylor-Rice-9 (Taylor Rice) as a politically relevant friend connected to acjohnson.
Added Chaddness (Chad Green) as a politically relevant friend connected to acjohnson.
Added blakielou55 (Blake Lewis) as a politically relevant friend connected to acjohnson.
Added BrendanWilliams (Brendan Williams) as a politically relevant friend connected to acjohnson.
Added Evan-Hill-3 (Evan Hill) as a politically relevant friend connected to acjohnson.
Added Mark-Allen-24 (Mark Allen) as a politically relevant friend connected to Sam-Cohen-22.
Added alexgar (Alex Garcia) as a politically relevant friend connected to Sam-Cohen-22.
Added erincary (E C) as a politically relevant friend connected to Sam-Cohen-22.
Added m4nduhh (Amanda Bauer) as a politically relevant friend connected to Sam-Cohen-22.
Added noahhkatz (Noah Katz) as a politically relevant friend connected to Sam-Cohen-22.
Added Hayden-Phillips-1 (Hayden Phillips) as a politically relevant friend connected to Andreanromero.
Added jgould11 (Jacob Gould) as a politically relevant friend connected to Andreanromero.
Added rjsilva2856 (Richard Silva) as a politically relevant friend connected to Andreanromero.
Added kelseande (Kelsey Anderson) as a politically relevant friend connected to Andreanromero.
Added Charlie-Fischer-2 (Charlie Fischer) as a politically relevant friend connected to Andreanromero.
Added Rprice14 (R P) as a politically relevant friend connected to todd-Hunter-16.
Added Marc-Goldberg-27 (Marc Goldberg) as a politically relevant friend connected to todd-Hunter-16.
Added Alicia-Taylor-19 (Alicia Taylor) as a politically relevant friend connected to todd-Hunter-16.
Added vincemorgannyc (Vincent Morgan) as a politically relevant friend connected to todd-Hunter-16.
Added Samuel-Rivers-3 (Samuel Rivers) as a politically relevant friend connected to todd-Hunter-16.
Added Ivette522 (Ivette Rodriguez) as a politically relevant friend connected to allenjwest.
Added Silas-White-2 (Silas White) as a politically relevant friend connected to allenjwest.
Added James-Mills-298 (James Mills) as a politically relevant friend connected to allenjwest.
Added LeMel-Humes (LeMel Humes) as a politically relevant friend connected to allenjwest.
Added Gary-Little (Gary Little) as a politically relevant friend connected to allenjwest.
Added Sam-Katz-2 (Sam Katz) as a politically relevant friend connected to ChrisJxx.
Added jrbland (James Bland) as a politically relevant friend connected to ChrisJxx.
Added LindseyGrahamWhite (Luke White) as a politically relevant friend connected to ChrisJxx.
Added Patrick-shriver-123 (Patrick Shriver) as a politically relevant friend connected to ChrisJxx.
Added H-Mills (Harold Mills) as a politically relevant friend connected to ChrisJxx.
Added Tommy-Oliver-3 (Tommy Oliver) as a politically relevant friend connected to Carl-Martin-1.
Added Jennifer-Williams-63 (Jennifer Williams) as a politically relevant friend connected to Carl-Martin-1.
Added Matteo-Baker (Matthew Baker) as a politically relevant friend connected to Carl-Martin-1.
Added mikemjackson312 (Mike Jackson) as a politically relevant friend connected to Carl-Martin-1.
Added Isabel-Dawson (Isabel Dawson) as a politically relevant friend connected to Carl-Martin-1.
Added BMoore007 (Brian Moore) as a politically relevant friend connected to Walter-Little-1.
Added dotsquiat (Thomas Goodwin) as a politically relevant friend connected to Walter-Little-1.
Added mrhitrecord (Joseph Lopez) as a politically relevant friend connected to Walter-Little-1.
Added allrise (Brandon Williams) as a politically relevant friend connected to Walter-Little-1.
Added tommerritt-1 (Tom Merritt) as a politically relevant friend connected to nicolenerd.
Added michael-1000000 (Michael Ferguson) as a politically relevant friend connected to nicolenerd.
Added scottbeale (Scott Beale) as a politically relevant friend connected to nicolenerd.
Added kevnull (Kevin Cheng) as a politically relevant friend connected to nicolenerd.
Added Stephen-Totilo (Stephen Totilo) as a politically relevant friend connected to Joel-Johnson.
Added LindsayHoward (Lindsay Howard) as a politically relevant friend connected to Joel-Johnson.
Added Kevin-Prince (Kevin Prince) as a politically relevant friend connected to Joel-Johnson.
Added yohelencho (Helen Cho) as a politically relevant friend connected to Joel-Johnson.
Added johnprice (John Price) as a politically relevant friend connected to Joel-Johnson.
Added Sean-Bowen-2 (Sean Bowen) as a politically relevant friend connected to djhardy.
Added Kevin-Bryant-1 (Kevin Bryant) as a politically relevant friend connected to djhardy.
Added BAGCEO (Jesse Brown) as a politically relevant friend connected to djhardy.
Added Danilady08 (Danielle Katz) as a politically relevant friend connected to djhardy.
Added Melvin-Francis (Melvin Francis) as a politically relevant friend connected to djhardy.
Added Robert-Howard-116 (Robert Howard) as a politically relevant friend connected to Rob-Anderson-87.
Added Dan-Hodges-6 (Dan Hodges) as a politically relevant friend connected to Rob-Anderson-87.
Added Jose-Perez-181 (Jose Perez) as a politically relevant friend connected to Rob-Anderson-87.
Added daruking (David King) as a politically relevant friend connected to Rob-Anderson-87.
Added AlbrightDC (Sally Albright) as a politically relevant friend connected to jessethomasjess3.
Added Robert-Browning-55 (Robert Browning) as a politically relevant friend connected to jessethomasjess3.
Added Nathaniel-Pearlman (Nathaniel Pearlman) as a politically relevant friend connected to jessethomasjess3.
Added KathyNChan (Kathy Chan) as a politically relevant friend connected to jessethomasjess3.
Added Werner-Vogels (Werner Vogels) as a politically relevant friend connected to jessethomasjess3.
Added johnwhelan68 (John Whelan) as a politically relevant friend connected to chriscarneyhair.
Added Jessica-Walsh (Jessica Walsh) as a politically relevant friend connected to chriscarneyhair.
Added Patrick-McKenna-4 (Patrick  McKenna) as a politically relevant friend connected to chriscarneyhair.
Added David-Levy-29 (David Levy) as a politically relevant friend connected to chriscarneyhair.
Added Kevin-Dann-4 (Kevin Dann) as a politically relevant friend connected to chriscarneyhair.
Added Jim-Moeller (Jim Moeller) as a politically relevant friend connected to Cyrus-Habib.
Added Marko-Liias (Marko Liias) as a politically relevant friend connected to Cyrus-Habib.
Added TParsi (Trita Parsi) as a politically relevant friend connected to Cyrus-Habib.
Added Steven-Fulop-1 (Steven Fulop) as a politically relevant friend connected to Cyrus-Habib.
Added Geoff-Simpson (Geoff Simpson) as a politically relevant friend connected to Cyrus-Habib.
Added TiffTPham (Tiffany Pham) as a politically relevant friend connected to MaxLugavere.
Added Roberto-Alter (Robert Alter) as a politically relevant friend connected to MaxLugavere.
Added rosey_baby (Rose Martinez) as a politically relevant friend connected to MaxLugavere.
Added TheTaylorHart (Taylor Hart) as a politically relevant friend connected to MaxLugavere.
Added Dominika-Juillet (Dominika Juillet) as a politically relevant friend connected to MaxLugavere.
Added Katherine_Brown (Kate Brown) as a politically relevant friend connected to Elizabeth-Brown-51.
Added Dan-Shapiro-2 (Dan Shapiro) as a politically relevant friend connected to Elizabeth-Brown-51.
Added Billy-McGill (Billy McGill) as a politically relevant friend connected to Elizabeth-Brown-51.
Added Andrew-Ward-7 (Andrew Ward) as a politically relevant friend connected to Elizabeth-Brown-51.
Added George-Richardson-2 (George Richardson) as a politically relevant friend connected to Elizabeth-Brown-51.
Added Julia-Bacha (Julia Bacha) as a politically relevant friend connected to Jenna-Arnold-1.
Added ki80cecconis (K I) as a politically relevant friend connected to Jenna-Arnold-1.
Added Dayle-Haddon (Dayle Haddon) as a politically relevant friend connected to Jenna-Arnold-1.
Added John-Donovan-29 (John Donovan) as a politically relevant friend connected to Jenna-Arnold-1.
Added JackShields405 (Jack Shields) as a politically relevant friend connected to Jenna-Arnold-1.
Added DSmythTheMyth18 (Daniel Smyth) as a politically relevant friend connected to Evan-Lloyd-2.
Added joypark (Joy Park) as a politically relevant friend connected to Evan-Lloyd-2.
Added Lawrence-Fox (Lawrence Fox) as a politically relevant friend connected to Evan-Lloyd-2.
Added JoshShapiro5 (Josh Shapiro) as a politically relevant friend connected to Evan-Lloyd-2.
Added John-Christenson-1 (John Christenson) as a politically relevant friend connected to Evan-Lloyd-2.
Added Avram-Mlotek (Avram Mlotek) as a politically relevant friend connected to John-Kelly-357.
Added Lyle-Harris (Lyle Harris) as a politically relevant friend connected to John-Kelly-357.
Added Steven-Walsh-5 (Steven Walsh) as a politically relevant friend connected to John-Kelly-357.
Added Kevin-Morgan-9150 (Kevin Morgan) as a politically relevant friend connected to John-Kelly-357.
Added David-Standridge (David Standridge) as a politically relevant friend connected to John-Kelly-357.
Added Matt-Wilson-130 (Matt Wilson) as a politically relevant friend connected to itsalexsmith.
Added Michael-Shaw-166 (Michael Shaw) as a politically relevant friend connected to itsalexsmith.
Added Erin-Wilson-1118 (Erin Wilson) as a politically relevant friend connected to itsalexsmith.
Added Rachel-Martin-23 (Rachel Martin) as a politically relevant friend connected to itsalexsmith.
Added jasonrubin78 (Jason Rubin) as a politically relevant friend connected to itsalexsmith.
Added DeepCutsHorror (Chris Wylie) as a politically relevant friend connected to Jeremy-Gilbert.
Added Jonathan-Meyer-7 (Jonathan Meyer) as a politically relevant friend connected to Jeremy-Gilbert.
Added Adrian-Gonzalez-44 (Adrian Gonzalez) as a politically relevant friend connected to Jeremy-Gilbert.
Added Dave-Johnson-75 (Dave Johnson) as a politically relevant friend connected to Jeremy-Gilbert.
Added JoeGilbert64 (Joe Gilbert) as a politically relevant friend connected to Jeremy-Gilbert.
Added John-Shaw-121 (John Shaw) as a politically relevant friend connected to Kevin-White-2.
Added Kara-Jackson-4 (Kara Jackson) as a politically relevant friend connected to Kevin-White-2.
Added doyleflush (Brian Doyle) as a politically relevant friend connected to Kevin-White-2.
Added bwils39 (Brian Wilson) as a politically relevant friend connected to Kevin-White-2.
Added mdengel88 (Matthew Engel) as a politically relevant friend connected to Kevin-White-2.
Added John-Harwood-5 (John Harwood) as a politically relevant friend connected to JakeSiewert1.
Added James-C-Gomez (James Gomez) as a politically relevant friend connected to JakeSiewert1.
Added JLSteiner (Joshua Steiner) as a politically relevant friend connected to JakeSiewert1.
Added Julius-Genachowski (Julius Genachowski) as a politically relevant friend connected to JakeSiewert1.
Added Adam-Schneider-70 (Adam Schneider) as a politically relevant friend connected to Lenny-Stern.
Added Scott-Pruitt (Scott Pruitt) as a politically relevant friend connected to Lenny-Stern.
Added Dave-Howard-18 (Dave Howard) as a politically relevant friend connected to Lenny-Stern.
Added John_Hoyt (John Hoyt) as a politically relevant friend connected to Lenny-Stern.
Added Thomas-Murphy-66 (Thomas Murphy) as a politically relevant friend connected to Christopher-Clarke-27.
Added Jenny-Harris-1 (Jenny Harris) as a politically relevant friend connected to Christopher-Clarke-27.
Added Justin-Wilson-210 (Justin Wilson) as a politically relevant friend connected to Christopher-Clarke-27.
Added Cynthia-Sestito (Cynthia Sestito) as a politically relevant friend connected to Christopher-Clarke-27.
Added James-Moore-238 (James Moore) as a politically relevant friend connected to Christopher-Clarke-27.
Added Annie-Lynch (Annie Lynch) as a politically relevant friend connected to Scott-Cohen-23.
Added bimo65 (Bill Morrison) as a politically relevant friend connected to Scott-Cohen-23.
Added hsu-paul (Paul Hsu) as a politically relevant friend connected to Scott-Cohen-23.
Added John-Duggan-22 (John Duggan) as a politically relevant friend connected to Scott-Cohen-23.
Added tkennedy10 (Thomas Kennedy) as a politically relevant friend connected to Scott-Cohen-23.
Added RobSolomon (Robert Solomon) as a politically relevant friend connected to Andrew-Solomon-16.
Added Tom-Murray-64 (Tom Murray) as a politically relevant friend connected to Andrew-Solomon-16.
Added CoryCap (C C) as a politically relevant friend connected to Andrew-Solomon-16.
Added Michael-Porter-229 (Michael Porter) as a politically relevant friend connected to Andrew-Solomon-16.
Added dsmitchell28 (David Mitchell) as a politically relevant friend connected to LouisianaMattBailey.
Added Ramsey-Green (Ramsey Green) as a politically relevant friend connected to LouisianaMattBailey.
Added Matt-Dean-1 (Matt Campbell) as a politically relevant friend connected to LouisianaMattBailey.
Added Bruce-Parker2 (Bruce Parker) as a politically relevant friend connected to LouisianaMattBailey.
Added Jim-Kessler-3 (Jim Kessler) as a politically relevant friend connected to LouisianaMattBailey.
Added Brian-Walsh-74 (Brian Walsh) as a politically relevant friend connected to TrevorKincaid.
Added Francis-Thomas (Francis Thomas) as a politically relevant friend connected to TrevorKincaid.
Added miketheharris (Mike Harris) as a politically relevant friend connected to TrevorKincaid.
Added schultzny (Eric Schultz) as a politically relevant friend connected to TrevorKincaid.
Added Brian-Greer (Brian Greer) as a politically relevant friend connected to TrevorKincaid.
Added jeremy79 (Jeremy Brown) as a politically relevant friend connected to Arshad-Hasan.
Added Joe-Russell-15 (Joe Russell) as a politically relevant friend connected to Arshad-Hasan.
Added David-Long-47 (David Long) as a politically relevant friend connected to Arshad-Hasan.
Added johnbarlow (John Emerson) as a politically relevant friend connected to Arshad-Hasan.
Added John-Austin-2 (John Austin) as a politically relevant friend connected to Arshad-Hasan.
Added Adam-Ray-10 (Adam Ray) as a politically relevant friend connected to David-Kramer-10.
Added Joseph-Feldman-5 (Joseph Feldman) as a politically relevant friend connected to David-Kramer-10.
Added Michael-Arrigo-3 (M A) as a politically relevant friend connected to David-Kramer-10.
Added Michael-Lombardo (Michael Lombardo) as a politically relevant friend connected to David-Kramer-10.
Added Mary-Smith-56 (Mary Smith) as a politically relevant friend connected to David-Kramer-10.
Added Allison-Ball (Allison Ball) as a politically relevant friend connected to alexhsmith.
Added Michael-Nolan-18 (Michael Nolan) as a politically relevant friend connected to alexhsmith.
Added studio_dad (Patrick Brown) as a politically relevant friend connected to alexhsmith.
Added melissabchan (Melissa Chan) as a politically relevant friend connected to alexhsmith.
Added Christopher-Kane-1 (Christopher Kane) as a politically relevant friend connected to alexhsmith.
Added Stephen-Greene-4 (Stephen Greene) as a politically relevant friend connected to David-Lloyd-2.
Added Elijah-Hutchinson (Elijah Hutchinson) as a politically relevant friend connected to David-Lloyd-2.
Added Evan-Jones (Evan Jones) as a politically relevant friend connected to David-Lloyd-2.
Added Sergio-Munoz-018 (Sergio Munoz) as a politically relevant friend connected to David-Lloyd-2.
Added Michael-Spencer-28 (Michael Spencer) as a politically relevant friend connected to David-Lloyd-2.
Added ipgray (Ian Gray) as a politically relevant friend connected to steelfloyd.
Added jiegel (Jeremy Siegel) as a politically relevant friend connected to steelfloyd.
Added Elizabeth-Smith-11954 (Elizabeth Smith) as a politically relevant friend connected to steelfloyd.
Added Todd-Smith-3 (Todd Smith) as a politically relevant friend connected to steelfloyd.
Added Gelobter (Michel Gelobter) as a politically relevant friend connected to Peter-Murray-32.
Added Drummond-Pike (Drummond Pike) as a politically relevant friend connected to Peter-Murray-32.
Added NinaKSimon (Nina Simon) as a politically relevant friend connected to Peter-Murray-32.
Added Ken-Weinstein-1 (Ken Weinstein) as a politically relevant friend connected to Peter-Murray-32.
Added Morgan-Simon (Morgan Simon) as a politically relevant friend connected to Peter-Murray-32.
Added William-Wade-23 (William Wade) as a politically relevant friend connected to allaspiaggia.
Added Michael-Myers-124 (Michael Myers) as a politically relevant friend connected to allaspiaggia.
Added David-Pinsky (David Pinsky) as a politically relevant friend connected to allaspiaggia.
Added Matt-Dunn-2 (Matt Dunn) as a politically relevant friend connected to allaspiaggia.
Added Sam-Benson-3 (Sam Benson) as a politically relevant friend connected to AshrafMarwan1.
Added Hayden-Frye-1 (Hayden Frye) as a politically relevant friend connected to AshrafMarwan1.
Added Arthur-Cohen-32 (Arthur Cohen) as a politically relevant friend connected to AshrafMarwan1.
Added Jacob-Katz3 (Jacob Katz) as a politically relevant friend connected to AshrafMarwan1.
Added Rashad-Moore-5 (Rashad Moore) as a politically relevant friend connected to Edward-Ellis-3.
Added WalterClark10 (Walter Clark) as a politically relevant friend connected to Edward-Ellis-3.
Added Nicole-Ng-8 (Nicole Ng) as a politically relevant friend connected to Edward-Ellis-3.
Added esimone32 (Simone Edwards) as a politically relevant friend connected to Edward-Ellis-3.
Added IanWMcLean (Ian McLean) as a politically relevant friend connected to Edward-Ellis-3.
Added Eric-Darnell (Eric Darnell) as a politically relevant friend connected to Malia-Ann.
Added mnm3714 (Emma Walker) as a politically relevant friend connected to Malia-Ann.
Added Eleanor-Wilson-7 (Eleanor Wilson) as a politically relevant friend connected to Malia-Ann.
Added Steven-Greene (Steven Greene) as a politically relevant friend connected to Malia-Ann.
Added Batboyben (Benjamin Thompson) as a politically relevant friend connected to Christopher-Ward-26.
Added JuanSerralles5 (Juan Serralles) as a politically relevant friend connected to Christopher-Ward-26.
Added cwilliams424 (Casey Williams) as a politically relevant friend connected to Christopher-Ward-26.
Added Samuelcohen12 (Samuel Cohen) as a politically relevant friend connected to Christopher-Ward-26.
Added BrianMTurner25 (Brian Turner) as a politically relevant friend connected to BenDMahon.
Added Donna-Jones-48 (Donna Jones) as a politically relevant friend connected to BenDMahon.
Added Benjamin-Clarke-13 (Benjamin Clarke) as a politically relevant friend connected to BenDMahon.
Added JStreak (Tim Johnson) as a politically relevant friend connected to BenDMahon.
Added david-n-12357 (david Newman) as a politically relevant friend connected to ThomasDietz.
Added Mattthanson (Matt Hanson) as a politically relevant friend connected to ThomasDietz.
Added Lauren-Reidd (Lauren Reid) as a politically relevant friend connected to ThomasDietz.
Added Joe-Walsh-30 (Joe Walsh) as a politically relevant friend connected to ThomasDietz.
Added Rachel-Robinson-112 (Rachel Robinson) as a politically relevant friend connected to John-Robinson-173.
Added David-Robinson-318 (David Robinson) as a politically relevant friend connected to John-Robinson-173.
Added mattkopec328 (Matt Kopec) as a politically relevant friend connected to John-Robinson-173.
Added David-Robinson-117 (David Robinson) as a politically relevant friend connected to John-Robinson-173.
Added John-Garcia-203 (John Garcia) as a politically relevant friend connected to Roberto-Campos-15.
Added Roberto-Campos-40 (Roberto Campos) as a politically relevant friend connected to Roberto-Campos-15.
Added Jose-Rodriguez141 (Jose Rodriguez) as a politically relevant friend connected to Roberto-Campos-15.
Added Ben-Pearson-7 (Ben Pearson) as a politically relevant friend connected to Roberto-Campos-15.
Added Kate-Baker (Kate Baker) as a politically relevant friend connected to James-Winebrake.
Added nivanov45 (Nikolay Ivanov) as a politically relevant friend connected to James-Winebrake.
Added Noah-Grossman (Noah Grossman) as a politically relevant friend connected to James-Winebrake.
Added Sean-Michael-11 (Sean Michael) as a politically relevant friend connected to James-Winebrake.
Added chelcherry (Chelsea Chen) as a politically relevant friend connected to James-Winebrake.
Added Alan-Marcus-2 (Alan Marcus) as a politically relevant friend connected to Abdul-Kareem.
Added Mohamed-Ismail (Mohamed Ismail) as a politically relevant friend connected to Abdul-Kareem.
Added mapler1924 (Pedro Cortes) as a politically relevant friend connected to Abdul-Kareem.
Added Trevor-McDonald-5 (Trevor McDonald) as a politically relevant friend connected to Abdul-Kareem.
Added Stephen-Jacobs-1 (Stephen Jacobs) as a politically relevant friend connected to Abdul-Kareem.
Added justinsunshine (Justin Sun) as a politically relevant friend connected to kevinyu.
Added Robert-Shaw-6 (Robert Shaw) as a politically relevant friend connected to kevinyu.
Added Kurt-Lee (Kurt Lee) as a politically relevant friend connected to kevinyu.
Added dougbarnard (Doug Barnard) as a politically relevant friend connected to kevinyu.
Added Morgan-Martin-8 (Morgan Martin) as a politically relevant friend connected to kevinyu.
Added Daniel-Greenberg-6 (Daniel Greenberg) as a politically relevant friend connected to Andy-Smith-12.
Added A-Long27 (Alexander Long) as a politically relevant friend connected to Andy-Smith-12.
Added Brad-Simon-1 (Brad Simon) as a politically relevant friend connected to Andy-Smith-12.
Added Henry-Scott (Henry Scott) as a politically relevant friend connected to Andy-Smith-12.
Added Austin-Taylor-1 (Austin Taylor) as a politically relevant friend connected to Andy-Smith-12.
Added Jake-Berman (Jake Berman) as a politically relevant friend connected to Henry-Sisson.
Added William-Smith-24 (William Smith) as a politically relevant friend connected to Henry-Sisson.
Added cjackson (Charlie Jackson) as a politically relevant friend connected to Henry-Sisson.
Added Scott-Crow-1 (Scott Crow) as a politically relevant friend connected to Henry-Sisson.
Added Sam_stone7 (Sam Stone) as a politically relevant friend connected to Henry-Sisson.
Added Mackbernard1 (Mack Bernard) as a politically relevant friend connected to chrisryan1050.
Added JIJComms (Jeffrey Johnson) as a politically relevant friend connected to chrisryan1050.
Added Courtney-Whitney-1 (Courtney Whitney) as a politically relevant friend connected to chrisryan1050.
Added Howard-Wolfson (Howard Wolfson) as a politically relevant friend connected to chrisryan1050.
Added Willie-Logan (Willie Logan) as a politically relevant friend connected to chrisryan1050.
Added Omar-Rahman-8 (Omar Rahman) as a politically relevant friend connected to Jonathan-Neman.
Added Jesse-Brown-8 (Jesse Brown) as a politically relevant friend connected to Jonathan-Neman.
Added xutony (Tony Xu) as a politically relevant friend connected to Jonathan-Neman.
Added Adam-Copeland-1 (Adam Copeland) as a politically relevant friend connected to Jonathan-Neman.
Added Richard-Day-16 (Richard Day) as a politically relevant friend connected to Fay-Hartog-Levin.
Added William-Morris-14 (William Morris) as a politically relevant friend connected to Fay-Hartog-Levin.
Added Patty-White-4 (Patty White) as a politically relevant friend connected to Fay-Hartog-Levin.
Added Wendy-Chamberlin-5 (Wendy Chamberlin) as a politically relevant friend connected to Fay-Hartog-Levin.
Added Richard-Day (Richard Day) as a politically relevant friend connected to Fay-Hartog-Levin.
Added Mo-Cowan (Mo Cowan) as a politically relevant friend connected to Deval-Patrick.
Added Stephen-Flaherty-8 (Stephen Flaherty) as a politically relevant friend connected to Deval-Patrick.
Added MJHegar (MJ Hegar) as a politically relevant friend connected to Deval-Patrick.
Added Michael-OLeary (Michael O'Leary) as a politically relevant friend connected to Deval-Patrick.
Added Thomas-Murphy-28 (Thomas Murphy) as a politically relevant friend connected to pgallen33.
Added Mitch-Lyons-1 (Mitch Lyons) as a politically relevant friend connected to pgallen33.
Added David-Kaplan-42 (David Kaplan) as a politically relevant friend connected to pgallen33.
Added MichaelWayneFoster (Michael Foster) as a politically relevant friend connected to pgallen33.
Added stephen-chambers-823 (Stephen Chambers) as a politically relevant friend connected to pgallen33.
Added tommyh70 (Tommy Hernandez) as a politically relevant friend connected to greghall12.
Added Vicente-Lopez (Vicente Lopez) as a politically relevant friend connected to greghall12.
Added jhsimmii (James Simmons) as a politically relevant friend connected to greghall12.
Added yochrismurphy (Chris Murphy) as a politically relevant friend connected to greghall12.
Added Carlos-Hernandez-12 (Carlos Hernandez) as a politically relevant friend connected to greghall12.
Added Daniel-White-10 (Daniel White) as a politically relevant friend connected to Ben-Mahon.
Added BankofLund (John Lund) as a politically relevant friend connected to Ben-Mahon.
Added Michael-Neumann-5 (Michael Neumann) as a politically relevant friend connected to Christian-Castillo-4.
Added josephdlyons (Joseph Lyons) as a politically relevant friend connected to Christian-Castillo-4.
Added onimon (Andrew Martin) as a politically relevant friend connected to Christian-Castillo-4.
Added johntallen01 (John Allen) as a politically relevant friend connected to Christian-Castillo-4.
Added Curtis-Jackson-9 (Curtis Jackson) as a politically relevant friend connected to Christian-Castillo-4.
Added natewlyon (Nathan Lyon) as a politically relevant friend connected to Rick-Klein-9.
Added Aclarkus (Andrew Clark) as a politically relevant friend connected to Rick-Klein-9.
Added RossAFreeman (Ross Freeman) as a politically relevant friend connected to Rick-Klein-9.
Added paythebadger (James Sheehan) as a politically relevant friend connected to Rick-Klein-9.
Added Taylor-Branch (Taylor Branch) as a politically relevant friend connected to BenSchott.
Added Dafrema (David Friedman) as a politically relevant friend connected to BenSchott.
Added Justin-Cole-7 (Justin Cole) as a politically relevant friend connected to BenSchott.
Added Timothy-Devlin-3 (Timothy Devlin) as a politically relevant friend connected to BenSchott.
Added LaToya-Thomas (LaToya Thomas) as a politically relevant friend connected to BenSchott.
Added Chris-Lee-116 (Chris Lee) as a politically relevant friend connected to David-Marsh.
Added Amelia-Simmons-4 (Amelia Simmons) as a politically relevant friend connected to David-Marsh.
Added drobinson389 (D R) as a politically relevant friend connected to David-Marsh.
Added Grace-Palmer-3 (Grace Palmer) as a politically relevant friend connected to David-Marsh.
Added Michael-Hogan-8 (Michael Hogan) as a politically relevant friend connected to David-Marsh.
Added C-D-1-55 (Crisanta Duran) as a politically relevant friend connected to Dylan-Roberts-1.
Added Alec-Garnett (Alec Garnett) as a politically relevant friend connected to Dylan-Roberts-1.
Added Janet-Buckner-7 (Janet Buckner) as a politically relevant friend connected to Dylan-Roberts-1.
Added JovanMelton (Jovan Melton) as a politically relevant friend connected to Dylan-Roberts-1.
Added Judith-Amabile (Judith Amabile) as a politically relevant friend connected to Dylan-Roberts-1.
Added John-Miller-112 (John Miller) as a politically relevant friend connected to Thomas-Berry-11.
Added Benjamin-Hoffman-2 (Benjamin Hoffman) as a politically relevant friend connected to Thomas-Berry-11.
Added Ben-Thomas-54 (Ben Thomas) as a politically relevant friend connected to Thomas-Berry-11.
Added Jackie-Smith-109 (Jackie Smith) as a politically relevant friend connected to Thomas-Berry-11.
Added Anthony-Bernal (Anthony Bernal) as a politically relevant friend connected to Brandon-English.
Added lpackard (Laura Packard) as a politically relevant friend connected to Brandon-English.
Added Sabrina-Singh-24 (Sabrina Singh) as a politically relevant friend connected to Brandon-English.
Added johnlee000 (John Lee) as a politically relevant friend connected to Brandon-English.
Added MalMarti (Malcolm Brown) as a politically relevant friend connected to Ozier-Muhammad.
Added marilynnance (Marilyn Nance) as a politically relevant friend connected to Ozier-Muhammad.
Added Derrick-Jackson-46 (Derrick Jackson) as a politically relevant friend connected to Ozier-Muhammad.
Added Rebecca-White-14 (Rebecca White) as a politically relevant friend connected to Ozier-Muhammad.
Added MunicRoberto (Robert Munic) as a politically relevant friend connected to saschapenn.
Added Orlandohz17 (Orlando Hernandez) as a politically relevant friend connected to saschapenn.
Added j_c12345 (J C) as a politically relevant friend connected to saschapenn.
Added butlerpaule (Paul Butler) as a politically relevant friend connected to saschapenn.
Added Jonathan-Glickman-1 (Jonathan Glickman) as a politically relevant friend connected to saschapenn.
Added Tom-Hawkins-5 (Tom Hawkins) as a politically relevant friend connected to jecummin.
Added Dan-Williams-58 (Dan Williams) as a politically relevant friend connected to jecummin.
Added Sarah-Miller-40 (Sarah Miller) as a politically relevant friend connected to jecummin.
Added JohnsonAChris (Christopher Johnson) as a politically relevant friend connected to jecummin.
Added Prescott-Burgess (Prescott Burgess) as a politically relevant friend connected to jecummin.
Added Harry-Thomas-37 (Harry Thomas) as a politically relevant friend connected to KLB0615.
Added Robert-Jones-649 (Robert Jones) as a politically relevant friend connected to KLB0615.
Added Cynthia-Cary-4 (Cynthia Cary) as a politically relevant friend connected to KLB0615.
Added Robert-Jones-1302 (Robert Jones) as a politically relevant friend connected to KLB0615.
Added StanleyLDavis (Stanley Davis) as a politically relevant friend connected to KLB0615.
Added Ryan-Trecartin (Ryan Trecartin) as a politically relevant friend connected to Ramesh-Srinivasan-2.
Added megangorillajedi (Megan Healy) as a politically relevant friend connected to Ramesh-Srinivasan-2.
Added brittanykaiserNYC (Brittany Kaiser) as a politically relevant friend connected to Ramesh-Srinivasan-2.
Added Dan-Ariely (Dan Ariely) as a politically relevant friend connected to Ramesh-Srinivasan-2.
Added John-Turner-483 (John Turner) as a politically relevant friend connected to Reema-Dodin.
Added jenny8lee (Jennifer Lee) as a politically relevant friend connected to Reema-Dodin.
Added BasimElkarra (Basim Elkarra) as a politically relevant friend connected to Reema-Dodin.
Added Shadi-Hamid (Shadi Hamid) as a politically relevant friend connected to Reema-Dodin.
Added Bob-Russell-22 (Bob Russell) as a politically relevant friend connected to Reema-Dodin.
Added Khanh-Nguyen-001 (Khanh Nguyen) as a politically relevant friend connected to Jayshah24.
Added Thomas-Culhane (Thomas Culhane) as a politically relevant friend connected to Jayshah24.
Added nshah323 (Nirav Shah) as a politically relevant friend connected to Jayshah24.
Added John-Nicholls-1 (John Nicholls) as a politically relevant friend connected to Jayshah24.
Added mcintosb (Ben McIntosh) as a politically relevant friend connected to Jayshah24.
Added emily-williams-2003 (Emily Williams) as a politically relevant friend connected to Macon-Phillips.
Added DanielDDavis (Daniel Davis) as a politically relevant friend connected to Macon-Phillips.
Added David-Wade-73 (David Wade) as a politically relevant friend connected to Macon-Phillips.
Added jessica4wine (Jessica Bell) as a politically relevant friend connected to Macon-Phillips.
Added BenWikler (Ben Wikler) as a politically relevant friend connected to Macon-Phillips.
Added AyooAK (Karen Jackson) as a politically relevant friend connected to Gary-Jackson-5.
Added mrfm9c (Matthew Frank) as a politically relevant friend connected to Gary-Jackson-5.
Added Manuel-Esquivel (Manuel Esquivel) as a politically relevant friend connected to Gary-Jackson-5.
Added ScottJensen1963 (Scott Jensen) as a politically relevant friend connected to Gary-Jackson-5.
Added Joseph-Bourgeois (Joseph Bourgeois) as a politically relevant friend connected to Nicholas-Johnson-24.
Added James-Williams-209 (James Williams) as a politically relevant friend connected to Nicholas-Johnson-24.
Added Michael-Bass-12 (Michael Bass) as a politically relevant friend connected to Nicholas-Johnson-24.
Added L_B_J (Ben Johnson) as a politically relevant friend connected to Nicholas-Johnson-24.
Added John-Allan-2 (John Allan) as a politically relevant friend connected to cs_parsons.
Added Andrew-Silverman (Andrew Silverman) as a politically relevant friend connected to cs_parsons.
Added Laura-Smith-0209 (Laura Smith) as a politically relevant friend connected to cs_parsons.
Added jamescamoliver (James Oliver) as a politically relevant friend connected to cs_parsons.
Added Mag_Walsh (Maggie Walsh) as a politically relevant friend connected to cs_parsons.
Added Helena-Moreno-2 (Helena Moreno) as a politically relevant friend connected to morrisdavidw.
Added Chris-Judd-12 (Chris Judd) as a politically relevant friend connected to morrisdavidw.
Added shawman42 (Don Shaw) as a politically relevant friend connected to morrisdavidw.
Added John-Neal-51 (John Neal) as a politically relevant friend connected to morrisdavidw.
Added Mitch-Landrieu (Mitch Landrieu) as a politically relevant friend connected to morrisdavidw.
Added Rachel_Ray1221 (Rachel Ray) as a politically relevant friend connected to John-Berger-10.
Added andymorris (Andy Morris) as a politically relevant friend connected to John-Berger-10.
Added ryannelson86 (Ryan Nelson) as a politically relevant friend connected to John-Berger-10.
Added Charles-Long-20 (Charles Long) as a politically relevant friend connected to John-Berger-10.
Added jreed1125 (Jordan Reed) as a politically relevant friend connected to John-Berger-10.
Added Michael-Caldwell-3 (Michael Caldwell) as a politically relevant friend connected to MichaelHarris.
Added Lucie-Williams (Lucie Williams) as a politically relevant friend connected to MichaelHarris.
Added Sydney-White-1 (Sydney White) as a politically relevant friend connected to MichaelHarris.
Added Kevib-Roy (Kevin Roy) as a politically relevant friend connected to MichaelHarris.
Added Michelle-Bittner (Michelle Roberts) as a politically relevant friend connected to MichaelHarris.
Added Jon-Ratliff (Jon Ratliff) as a politically relevant friend connected to tsaboston.
Added David-Watkins-18 (David Watkins) as a politically relevant friend connected to tsaboston.
Added WalterWilliams (Walter Williams) as a politically relevant friend connected to tsaboston.
Added ian-Quigley-1 (Ian Quigley) as a politically relevant friend connected to tsaboston.
Added Robert-Smith-50 (Robert Smith) as a politically relevant friend connected to tsaboston.
Added foremanm (Mike Foreman) as a politically relevant friend connected to xatgm.
Added Paul-Lederer-1 (Paul Lederer) as a politically relevant friend connected to xatgm.
Added StickyShaw (Robert Shaw) as a politically relevant friend connected to xatgm.
Added Frank-Fay (Frank Fay) as a politically relevant friend connected to xatgm.
Added Jose-Ramos-2 (Jose Ramos) as a politically relevant friend connected to xatgm.
Added RickyDillard1 (Ricky Dillard) as a politically relevant friend connected to thedavidbrand.
Added Patrick-Walker-102 (Patrick Walker) as a politically relevant friend connected to thedavidbrand.
Added MikeyBATL (Michael Brunson) as a politically relevant friend connected to thedavidbrand.
Added GavinBrown1914 (Gavin Brown) as a politically relevant friend connected to thedavidbrand.
Added James-Walker-231 (James Walker) as a politically relevant friend connected to thedavidbrand.
Added Sam-Thompson-21 (Sam Thompson) as a politically relevant friend connected to Max-Rosenthal-2.
Added jenpage (Jennifer Page) as a politically relevant friend connected to Max-Rosenthal-2.
Added Andrew-Hansen-27 (Andrew Hansen) as a politically relevant friend connected to Max-Rosenthal-2.
Added Johnny-King-4 (Johnny King) as a politically relevant friend connected to Max-Rosenthal-2.
Added DavidBussey (David James) as a politically relevant friend connected to Max-Rosenthal-2.
"""
# Parse and create edges directly from the data
edges = []
node_labels = {}  # Store labels for display
for line in data.strip().split("\n"):
    if line.startswith("Added"):
        parts = line.split()
        friend_username = parts[1]
        friend_display_name = parts[2].strip('()') + " " + parts[3].strip('()')
        connected_to_username = parts[-1].strip('.')
        edges.append((connected_to_username, friend_username))
        # Also gather display names for later usage
        node_labels[friend_username] = friend_display_name
        node_labels[connected_to_username] = connected_to_username  # Replace with actual display name if available

# Create the graph
G = nx.Graph()
G.add_edges_from(edges)

# Compute basic stats
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()

# Find the node with the maximum degree
max_degree_node = max(G.degree, key=lambda x: x[1])
max_degree_node_name = node_labels[max_degree_node[0]]
max_degree = max_degree_node[1]

print(f"Total number of nodes: {num_nodes}")
print(f"Total number of edges: {num_edges}")
print(f"Node with the most connections: {max_degree_node_name} with {max_degree} connections")

# Choose a root node for layer calculation
root_node = 'Valerie-Jarrett-2' 

# Calculate the shortest path lengths from root_node to all other nodes
layer_counts = nx.single_source_shortest_path_length(G, root_node)

# Count the number of nodes in each layer
layer_distribution = {}
for node, layer in layer_counts.items():
    if layer in layer_distribution:
        layer_distribution[layer] += 1
    else:
        layer_distribution[layer] = 1

# Output the number of nodes per layer
for layer, count in sorted(layer_distribution.items()):
    print(f"Layer {layer}: {count} nodes")
